### PR TITLE
Updated optimization under uncertainty

### PR DESCRIPTION
**Pull request by anirban-chaudhuri**
- Updated OUU to run with new interface
- Added optimize interface for petri nets
- Added plotting utilities
- Updated december demo

### CODE REVIEW

**Review by djinnome — APPROVED** [review]
I ran the notebook all the way through, and it produced no errors and all the correct plots. It is ready to merge IMHO

**Comment by anirban-chaudhuri** [comment]
I am not sure I understand why we need to merge the ensemble changes into this branch. I have not made any changes to the ensemble codes and there are no merge conflicts.

**Comment by djinnome** [comment]
Merged main into ac-ouu-DecDemo.  Confirmed scenario2_ouu runs without errors and generates correct plots.  Removed extraneos scenario 2 variants and renamed scenario2_ouu to scenario2

**Comment by djinnome** [comment]
@SamWitty  do you want to make the final call on squash & merge?

**Comment by djinnome** [comment]
> I am not sure I understand why we need to merge the ensemble changes into this branch. I have not made any changes to the ensemble codes and there are no merge conflicts.

Oh, because I already accepted the ensemble changes PR into `main`.  I think it is bad software hygiene to accept a PR if the branch is behind main.

I suppose the "right" thing to do is rebase your branch so it doesn't get added to the git history, but opinions differ.

**Comment by anirban-chaudhuri** [comment]
Ok sounds good. Yes, it seems rebasing would be better.

**Comment by anirban-chaudhuri** [comment]
There are still some empty or unfinished notebooks in the Decemeber demo that got pushed from main. I had deleted everything except scenario 2. Should we remove them again? I don't think we need to show more than one notebook.

**Pull request merged**
