### PR TITLE
438 add various interventions to interfacesipynb

### LINKED ISSUE #438: Add various interventions to interfaces.ipynb
Currently the interfaces.ipynb example usage only includes `sample` with basic arguments describing how to simulate forward in time. However, our `sample` interface also includes interventions of various types.

Specifically, this addressing this issue would add the following:

- [x] `static_parameter_interventions`
- [x] `static_state_interventions`
- [x] `dynamic_parameter_interventions`
- [x] `dynamic_state_interventions`

### PR DESCRIPTION
**Pull request by sabinala**
Closes #438

### CODE REVIEW

**Comment by SamWitty** [comment]
@sabinala , could you resolve conflicts and then tag me when this is ready for review again? Thanks!

**Comment by sabinala** [comment]
@SamWitty I resolved the branch conflicts, and then went to run the notebook again and now I'm getting an error when trying to `sample` with interventions. I'm confused because I thought this came up and was resolved, but please see: https://github.com/ciemss/pyciemss/issues/524

**Comment by SamWitty** [comment]
I get an error with this notebook at the dynamic parameter intervention (which explains why the notebook CI test fails), but it is successfully running the static interventions. See my comment about a fresh environment in #524.

**Comment by SamWitty** [comment]
@sabinala , I fixed the notebook up to `optimize`. I believe in your merge you erased changes to the API that @anirban-chaudhuri had made. Once you resolve your PyCIEMSS and ChiRho version errors you should be able to pick up from there.

**Comment by sabinala** [comment]
@SamWitty Thanks, trying that now

**Comment by SamWitty** [comment]
Adding @anirban-chaudhuri as a reviewer to confirm that this did not revert previous changes to `optimize`. Once it's ready for Anirban's approval, we can merge.

**Comment by sabinala** [comment]
@SamWitty starting with a fresh environment did fix the errors I was getting before. Are you no longer getting an error for `dynamic_parameter_intervention`? When I run it with `make_var_threshold` defined as:
```python
def make_var_threshold(var: str, threshold: torch.Tensor):
    def var_threshold(time, state):
        return state[var] - threshold
    return var_threshold
```
I get a `KeyError`: 
```python
File ~/anaconda3/lib/python3.10/site-packages/pyro/infer/predictive.py:55, in <dictcomp>(.0)
     52         collected.append(trace)
     53     else:
     54         collected.append(
---> 55             {site: trace.nodes[site]["value"] for site in return_site_shapes}
     56         )
     58 if return_trace:
     59     return collected

KeyError: 'parameter_intervention_value_p_cbeta_0'
```

**Review by anirban-chaudhuri — COMMENTED** [review]
The last part with optimize is the old version. We need to copy over the newer notebook implementation for `optimize` from `interfaces.ipynb` from `main`.

**Comment by sabinala** [comment]
@SamWitty @anirban-chaudhuri This notebook is ready to go and includes the new `optimize` interface implementations

**Comment by sabinala** [comment]
> @SamWitty @anirban-chaudhuri This notebook is ready to go and includes the new `optimize` interface implementations

Nevermind...cannot get the notebook test to pass :(

**Comment by SamWitty** [comment]
@sabinala , unfortunately the CI does not return very informative error messages for the notebook tests. When I run the `test_notebooks.sh` script locally I get an error `ERROR docs/source/interfaces.ipynb::Cell 0 - jupyter_client.kernelspec.NoSuchKernel: No such kernel named pyciemss` which is a bit more informative. It looks like you made some accidental changes to the kernel from `python3` to `pyciemss`, which doesn't exist in the CI build.

**Review by SamWitty — APPROVED** [review]
I believe the CI issues are now addressed.

**Comment by SamWitty** [comment]
@sabinala , this issue looks slightly more nuanced. I'll figure it out. Please hold off on making more commits.

**Review by SamWitty — APPROVED** [review]

**Pull request merged**
