### PR TITLE
Recover demo notebook to add back optimization

### PR DESCRIPTION
**Pull request by anirban-chaudhuri**

### CODE REVIEW

**Comment by anirban-chaudhuri** [comment]
@djinnome Can you take a look at this PR to see why S0 in the demo notebook takes incorrect values? The same AMR seems to work in the ensemble demo notebook.

**Comment by SamWitty** [comment]
Waiting to review this until @JosephCottam has had a chance to add back in the visualization outputs.

**Comment by anirban-chaudhuri** [comment]
> Waiting to review this until @JosephCottam has had a chance to add back in the visualization outputs.

I have already added the visualization outputs. I added back the ones Joseph had and fixed the visuals to only plot the states.

**Comment by anirban-chaudhuri** [comment]
> > Waiting to review this until @JosephCottam has had a chance to add back in the visualization outputs.
> 
> I have already added the visualization outputs. I added back the ones Joseph had and changed the visuals to only plot the states.

The code for plotting was already included, but for some reason the actual plots don't show up online. I just pushed the demo notebook with the plots again, but it still doesn't show up online.

**Comment by JosephCottam** [comment]
While verifying this PR had what I made, I encountered an intermittent issue with the re-running plots (#262).  I accidentally pushed that fix to this branch.

**Review by SamWitty — APPROVED** [review]
looks good to me.

**Pull request merged**
