### PR TITLE
273 error required amr has no initials

### LINKED ISSUE #273: Error required: AMR has no initials
A clear error should be raised when the AMR has no initials.

### LINKED ISSUE #287: Error required: Number of transitions should equal number of rate laws
Throw an error when this happens ^

### LINKED ISSUE #288: Error required: Syntax error in parsing the AMR
When the AMR has colons instead of underscores, or there are other issues make sure to mark it clearly that the AMR has an invalid symbol.

### PR DESCRIPTION
**Pull request by sabinala**
This pull request adds a function to PetriNetODE interfaces called `run_petri_model_checks` that checks that the model AMR (a) is readable/formatted correctly, (b) that the number of transitions matches the number of rate laws, and (c) includes initial conditions for each state variable.

This addresses a few issues.
Closes #273 
Closes #288 
Closes #287

### CODE REVIEW

**Comment by sabinala** [comment]
The additional models and notebook can be deleted once this PR is accepted.

**Comment by djinnome** [comment]
Hey @sabinala do you want to fix the conflicts that must be resolved?

**Comment by sabinala** [comment]
@djinnome I'm not sure what to do here. It seem like a lot of this work has been covered by what Joseph has built for checking models/AMRs, but the conflicting files like `syndata_generate_and_test.ipynb` and `synthetic_data_with_custom_models.ipynb` are no longer in use.

**Comment by SamWitty** [comment]
Closing this PR as it appears to be out of date. Please reopen if you believe this was done as a mistake.

**Pull request closed without merging**
