### PR TITLE
Fixing issue in deriv method

### PR DESCRIPTION
**Pull request by djinnome**

### CODE REVIEW

**Comment by djinnome** [comment]
Blocked on https://github.com/indralab/mira/issues/183

**Comment by djinnome** [comment]
It turns out that AMR json files containing a `lambda` parameter can't currently be converted to a mira model due to sympy interpreting rate laws containing `lambda` as an anonymous function rather than a parameter.
I manually annotated the AMR json file to rename the reserved word.

**Review by SamWitty — APPROVED** [review]
Looks good to me. Soon we'll want to remove support for mira models.

**Comment by djinnome** [comment]
do you mean serializing/deserializing DynamicalSystem to AMR without mira dependencies?

**Pull request merged**
