### PR TITLE
Scenario 1 expansion 

### PR DESCRIPTION
**Pull request by VigneshSella**

### CODE REVIEW

**Review by anirban-chaudhuri — COMMENTED** [review]
The output from the TA4 interface when plotting should return a dict. Can you update the calls to use the latest interface with visualizations built-in?

**Comment by anirban-chaudhuri** [comment]
> The output from the TA4 interface when plotting should return a dict. Can you update the calls to use the latest interface with visualizations built-in?

See https://github.com/ciemss/pyciemss/blob/scenario1-expansion/notebook/integration_demo/demo.ipynb for reference

**Comment by anirban-chaudhuri** [comment]
Can you pull the latest merge to main and update the interface calls? The updated version has everything consistent for the return types of the TA4 interfaces.

**Comment by VigneshSella** [comment]
> Can you pull the latest merge to main and update the interface calls? The updated version has everything consistent for the return types of the TA4 interfaces.

Will do this weekend or Monday morning. Shouldn't cause any issue, other than changing how plotting works.

**Review by anirban-chaudhuri — APPROVED** [review]

**Pull request merged**
