### PR TITLE
fixing synth_data_utils

### PR DESCRIPTION
**Pull request by sabinala**
I fixed the bugs in this utils file. Probably won't need this again anyway :)

### CODE REVIEW

**Comment by sabinala** [comment]
The corresponding issue and branch should be closed if the pull request is accepted

**Comment by SamWitty** [comment]
> The corresponding issue and branch should be closed if the pull request is accepted

@sabinala , you can use GitHub's `closing` keywords to automate this when you create a PR. See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by djinnome** [comment]
@sabinala Do you want to resolve these stale conflicts?

**Comment by sabinala** [comment]
@djinnome I think this is a depricated issue, the `synth_data_utils` file does not exist in the `main` branch anymore. I recommend deleting this issue. Let me know if you think differently.

**Comment by djinnome** [comment]
Is there anything from synth_data_utils that you want to keep?

**Comment by sabinala** [comment]
No, that's not necessary.

**Comment by sabinala** [comment]
We're going to create synthetic data in another way, in response to this issue #448

**Comment by SamWitty** [comment]
Closing this PR and issue at @sabinala 's description above. Please reopen if you believe this was closed by mistake.

**Pull request closed without merging**
