### PR TITLE
Sa ensemble eval

### PR DESCRIPTION
**Pull request by djinnome**
Thanks to all the effort @sabinala  put into the evaluation ensemble, I was able to fix the last few remaining issues, and we now have calibrated ensemble models composed of the `SEIV`, `SEIVCDU`, and `SEIRHDS_ww` models.  There may be a little bit of cleanup and writeup necessary, but there should be no more blockers.

For the SEIV and SEIVCDU models, the main blocker was finding reasonable priors.  For the SEIRHDS_ww model, the main blockers were converting the observables to compartments, and finding reasonable priors.  

The calibrated ensemble results (both trajectories and quantiles) are in a new subdirectory called `ensemble_results`

### CODE REVIEW

**Comment by anirban-chaudhuri** [comment]
@djinnome Could you make sure that the reformatting to CDC version made it to the ensemble quantile results? 
- See pull request #316 for details. @sabinala reviewed the PR so she also knows about how to get it to that format.
- See cell 7 in https://github.com/ciemss/pyciemss/blob/main/notebook/integration_demo/demo_ensemble.ipynb
- The integration demo_ensemble notebook in the current branch shows an error. Could you take a look at that too?
Let me know if you have questions regarding the file format that MITRE requires for evaluation or if you see any issues.

**Comment by djinnome** [comment]
Hi @anirban-chaudhuri I merged main into this branch last night, so it *should* have the re-formatted quantile results in 
https://github.com/ciemss/pyciemss/blob/sa-ensemble-eval/notebook/ensemble_eval_sa/ensemble_results/calibrated_ensemble_quantiles.csv

Let me know if anything looks funny to you.


> @djinnome Could you make sure that the reformatting to CDC version made it to the ensemble quantile results?
> 
> * See pull request [Adding functionality to manipulate csv to required CDC format #316](https://github.com/ciemss/pyciemss/pull/316) for details. @sabinala reviewed the PR so she also knows about how to get it to that format.
> * See cell 7 in https://github.com/ciemss/pyciemss/blob/main/notebook/integration_demo/demo_ensemble.ipynb
> * The integration demo_ensemble notebook in the current branch shows an error. Could you take a look at that too?
>   Let me know if you have questions regarding the file format that MITRE requires for evaluation or if you see any issues.

**Comment by anirban-chaudhuri** [comment]
> Hi @anirban-chaudhuri I merged main into this branch last night, so it _should_ have the re-formatted quantile results in https://github.com/ciemss/pyciemss/blob/sa-ensemble-eval/notebook/ensemble_eval_sa/ensemble_results/calibrated_ensemble_quantiles.csv
> 
> Let me know if anything looks funny to you.
> 
> > @djinnome Could you make sure that the reformatting to CDC version made it to the ensemble quantile results?
> > 
> > * See pull request [Adding functionality to manipulate csv to required CDC format #316](https://github.com/ciemss/pyciemss/pull/316) for details. @sabinala reviewed the PR so she also knows about how to get it to that format.
> > * See cell 7 in https://github.com/ciemss/pyciemss/blob/main/notebook/integration_demo/demo_ensemble.ipynb
> > * The integration demo_ensemble notebook in the current branch shows an error. Could you take a look at that too?
> >   Let me know if you have questions regarding the file format that MITRE requires for evaluation or if you see any issues.

That file is the original format that MITRE wanted and they still want that in case they need to change more stuff. 
However, they also wanted file to be reformatted as close as possible to the CDC eval format. The CDC reformatting is not a part of the interface at the moment since TA3 does not get the information passed down (dates, location, etc.). Check out the demo_ensemble notebook for how to do it in the notebook environment with extra inputs from the user. Specifically, check the following:
- See pull request https://github.com/ciemss/pyciemss/pull/316 for details. @sabinala reviewed the PR so she also knows about how to get it to that format.
- See cell 7 in https://github.com/ciemss/pyciemss/blob/main/notebook/integration_demo/demo_ensemble.ipynb

**Comment by anirban-chaudhuri** [comment]
Can you also check why the demo_ensemble notebook is not showing up?
https://github.com/ciemss/pyciemss/blob/sa-ensemble-eval/notebook/integration_demo/demo_ensemble.ipynb

**Comment by djinnome** [comment]
@anirban-chaudhuri I fixed the conflict (usual notebook metadata BS).

**Pull request closed without merging**
