### PR TITLE
293 enable an all but option on trajectory plot

### PR DESCRIPTION
**Pull request by JosephCottam**
Changed 'subset' to be 'keep' and added 'drop' to the trajectories example.  I think I got all of the related notebooks too.

### CODE REVIEW

**Comment by JosephCottam** [comment]
Main isn't passing (at least some of) these tests on my computer right now either.  I'm not sure how to proceed.

**Review by VigneshSella — CHANGES_REQUESTED** [review]
I believe main needs to be pulled into your branch before request a merge. There's new things in the demo notebook (added after the quantiles update) on main, that are not reflected in this branch.

**Comment by JosephCottam** [comment]
Back up to date with main and passing all tests again.

**Review by ShantMahserejian — APPROVED** [review]

**Review by VigneshSella — APPROVED** [review]
Looks good to me, and addresses original issue perfectly.

**Pull request merged**
