### PR TITLE
adding check on num_samples

### LINKED ISSUE #451: Type checking on `sample` for `num_samples`
Need several tests for `num_samples`:

- [ ] `num_samples = 3` as an `int`
- [ ] `num_samples = 3.0` as a 'float`
- [ ] `num_samples = 3.1` as a 'float`
- [ ] `num_samples = torch.tensor(3)` as tensor
- [ ] `num_samples = torch.tensor([3])` as tensor
- [ ] `num_samples = torch.tensor(3.0)` as tensor
- [ ] `num_samples = torch.tensor([3.0])` as tensor
- [ ] `num_samples = None`
- [ ] `num_samples = -3`
- [ ] `num_samples = "a"`
- [ ] `num_samples = [3, 4, 5]` as an array

We check that the output either "fails gracefully" with an informative error message, or warns us that it has converted to an `int`.

### PR DESCRIPTION
**Pull request by sabinala**
This PR adds an assert statement (see code below) in both `sample` and `ensemble_sample` that will give the error message: "num_samples must be a positive integer." if `num_samples` is not a positive integer.

```python
# Check that num_samples is a positive integer
assert isinstance(num_samples, int) and num_samples > 0, "num_samples must be a positive integer."
```

Closes #451

### CODE REVIEW

**Comment by SamWitty** [comment]
@sabinala , as discussed in our call yesterday, could you please change these assertions to the following:

```
if condition:
    raise ValueError("description")
```

**Comment by sabinala** [comment]
@djinnome I've changed the `assert` statement to an `if` statement that raises a `ValueError`, and now this PR is ready for review.

**Comment by djinnome** [comment]
Can you also add a unit test that gives a nonpositive interger and a float and a tensor int to num_samples and assert that a ValueError is raised?

**Comment by sabinala** [comment]
@djinnome unit tests for `sample` and `ensemble_sample` error messages are now in their own files inside of `tests` and all tests are passing!

**Review by djinnome — APPROVED** [review]
Fabulous, @sabinala !

**Pull request merged**
