### PR TITLE
Add support for many more MIRA probonto distributions

### PR DESCRIPTION
**Pull request by SamWitty**
See #590 for the original PR from @liunelson .

### CODE REVIEW

**Comment by SamWitty** [comment]
@liunelson , why are some of the types for the parameters `Dict[str, Union[float, list]]` and not just `Dict[str, float]`?

See e.g. `mira_betabinomial_to_pyro`

**Comment by SamWitty** [comment]
@liunelson , it looks like you used `Gamma` where you meant to use `InverseGamma`.

Also, I'd like to add some tests to ensure these mappings are completed correctly. Do you have any example AMRs that use some of these new distributions?

**Comment by liunelson** [comment]
> @liunelson , why are some of the types for the parameters `Dict[str, Union[float, list]]` and not just `Dict[str, float]`?
> 
> See e.g. `mira_betabinomial_to_pyro`

The Pyro Binomial distribution expects a `list` for either the `probs` or `logs` arguments 
https://docs.pyro.ai/en/stable/distributions.html#binomial

You're right about the BetaBinomial distribution; it just wants `Dict[str, float]`; I copy-and-pasted the type hints from the Binomial one.

**Comment by liunelson** [comment]
I don't actually have any example of AMRs handy that use _all_ these different probability distributions.

However, MIRA has this test but it just directly invokes a `LogNormal1` distribution out of the blue.
https://github.com/gyorilab/mira/blob/7d98f519f06a471284009b56e7af9b0d8f4201e9/tests/test_modeling/test_petri.py#L38

**Comment by liunelson** [comment]
Besides the type hinting of the `BetaBinomial` function, everything else looks fine to me.

**Review by anirban-chaudhuri — APPROVED** [review]

**Pull request merged**
