### PR TITLE
371 visuals/schemas not included upon using pip install

### PR DESCRIPTION
**Pull request by JosephCottam**

### CODE REVIEW

**Comment by JosephCottam** [comment]
@SamWitty I think these commits fix the issue that @fivegrant was having with install. Since you setup the original testing infrastructure, I think you should look at this.  When/if we merge this PR, we should do a new pyciemss release (the cfg file already bumps up to 0.0.3) because it will install parts it was not installing before.

@sabinala I had to change a few bits in the complexvid module to get all the tests to pass.  Please look at it and approve if these changes work for you.  

Note:  I did not change the test suite because when I changed the command that installed pyciemss, tests that looked for the schema files failed and started to pass after my changes.  From this, I don't think updated tests were needed.

**Review by djinnome — APPROVED** [review]
I think ComplexVID does not need to be maintained in our repo, but @sabinala is working on that in another PR.

**Review by djinnome — CHANGES_REQUESTED** [review]
I am getting the following error when running `pip install -e .` in `codespace`

```python
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.6.1 requires jsonschema<4.18.0,>=4.10.0, but you have jsonschema 4.19.0 which is incompatible.
```

This is particularly weird, because neither `jsonschema` nor `poetry` is mentioned in `setup.cfg`

**Review by djinnome — APPROVED** [review]
OK, the problem was resolved by setting:  

 `jupyter-events==0.6.0` and `jsonschema==4.17.3`

**Pull request merged**
