### PR TITLE
adding check for num_iterations in calibrate

### LINKED ISSUE #456: Type checking on `calibrate` for `num_iterations`
Writing an `assert` statement to check that `num_iterations` is a positive integer inside of `calibrate`.

### PR DESCRIPTION
**Pull request by sabinala**
This PR adds an assert statement (see code below) in `calibrate` that will give the error message: "num_iterations must be a positive integer." if `num_iterations` is not a positive integer.

```python
# Check that num_iterations is a positive integer
assert isinstance(num_iterations, int) and num_iterations > 0, "num_iterations must be a positive integer."
```

Closes #456

### CODE REVIEW

**Comment by SamWitty** [comment]
@sabinala , as discussed in our call yesterday, could you please change these assertions to the following:

```
if condition:
    raise ValueError("description")
```

**Comment by sabinala** [comment]
@djinnome I've changed the `assert` statement to an `if` statement that raises a `ValueError`, and now this PR is ready for review.

**Comment by djinnome** [comment]
Hi @sabinala please add a unit test in `test_interfaces.py` that asserts that providing a `float`, or negative `int` or `0` or `tensor(int)` raises an error when used as input to the `num_samples` parameter, and providing a positive `int` does not raise an error.

**Comment by sabinala** [comment]
Hi @djinnome can you please take a look at the unit test I added to `test_interfaces.py`? It appears all of the checks are passing, but I would appreciate your feedback.

**Comment by sabinala** [comment]
@djinnome unit tests for `calibrate` error messages are in their own file in `tests`, and all tests are passing here too.

**Review by djinnome — APPROVED** [review]
This is great, @sabinala Thanks!

**Pull request merged**
