### PR TITLE
219 test all models in amr to see if they can be loaded

### PR DESCRIPTION
**Pull request by djinnome**

### CODE REVIEW

**Review by JosephCottam — APPROVED** [review]
I took over development...somebody else should review it now.

**Comment by JosephCottam** [comment]
@djinnome I would appreciate some help diagnosing the current issue on this branch.

It seems that the 'calibrate and sample' might have changed its interface...or that the models need to be updated...or something.  I'm not sure where to look to figure out the next step. Any advise?

**Comment by djinnome** [comment]
I believe many of these errors were caused by sympytorch. What happens if you run the amr tests with `compile_rate_law_p=False`

**Comment by JosephCottam** [comment]
Adding `compile_rate_law_p=False` did not change the number of errors (10 fail).

Though true, it seems something that was returning a dataframe now returns a dictionary, that "something" seems to be `solutions_to_observations` in `interface_utils`.  (The test itself was already adapted to look for dicts instead of dataframes, see line 117, and that is how I got some tests passing yesterday).  Is there a *something* that is causing it to sometimes return a dataframe and sometimes a dictionary?  How would I know which to expect (or possibly, now to tell `solutions_to_observations` which to expect)?

**Comment by JosephCottam** [comment]
Add a test that FAILS if things that used to fail now pass, include in the prompt the command line that updates the expected-pass/fail list.

**Comment by JosephCottam** [comment]
@djinnome I extended this with the "unexpected success" message we talked about.  

I haven't been able to figure out how to get calibrate & sample working.  Can you take try to fix that call?  Currently they all fail with messages I don't know how to interpret.

**Comment by djinnome** [comment]
@JosephCottam Should we resolve this or just retire it?

**Pull request closed without merging**
