### PR TITLE
Removing COmplexVID as it is no longer in use.

### PR DESCRIPTION
**Pull request by sabinala**
Deleted three files adapted from the original COmplex-VID code, and the notebook that used them (for scenario 3 in hackathon prep).

### CODE REVIEW

**Comment by SamWitty** [comment]
@sabinala , could you please resolve the merge conflicts?

**Comment by sabinala** [comment]
@SamWitty I would love to, but I'm not sure how to. When I try merging the `sa-delete-complexvid` branch, I get this:

```
(base) WE47357:pyciemss altu809$ git fetch origin
(base) WE47357:pyciemss altu809$ git pull origin sa-delete-complexvid
From https://github.com/ciemss/pyciemss
 * branch            sa-delete-complexvid -> FETCH_HEAD
Already up to date.
(base) WE47357:pyciemss altu809$ git merge sa-delete-complexvid
Already up to date.
(base) WE47357:pyciemss altu809$ git status
On branch sa-delete-complexvid
Your branch is up to date with 'origin/sa-delete-complexvid'.

nothing to commit, working tree clean
```

But I was expecting `git status` to give me a list of conflicting files? All I am trying to do is delete those three files listed.

**Comment by SamWitty** [comment]
Try `git pull origin main`

**Comment by sabinala** [comment]
Thanks, I think we're good to go.

**Comment by SamWitty** [comment]
Closing, as it's superseded by #396

**Pull request closed without merging**
